### ISSUE TITLE
Instructions/documentation

### ISSUE THREAD

**Issue by krusk** [drohreo/spPeoplePicker-ng-directive#1]
Do you have instructions/documentation for using this directive?

**Comment by ohritz** [comment]
Hi. 
Im sorry but i hav'nt had the time to update the code and make it easier to use. 
But the solution on git is a demo from a blog post i wrote.
You can find that at sohanfdev.wordpress.com

Hope it can shed some light on how to use it.
Maybe in time ill be able to refractor the code into a module that can be used more easily.

**Comment by krusk** [comment]
Thank you for publishing this directive, and I appreciate all your work!

Regards,

Kelly

Date: Wed, 17 Jun 2015 13:25:15 -0700
