### ISSUE TITLE
id = peoplePickerDivX

### ISSUE THREAD

**Issue by getsetbro** [drohreo/spPeoplePicker-ng-directive#3]
If you had more than one picker on the page wouldn't they all have the same ID of "peoplePickerDivX"?

**Comment by ohritz** [comment]
what the current implementation does is get the element peoplePickerDivX from the template, and change the id.. with a counter which is increased for every invocation of the directive..

Im currently working on a different implementation.. which is in branch "1.dev"  its still not done..
But Ive refactored the unique Id implementation into a template function instead, and get that Id in the link function for initiliazing the peoplepicker
